nikgraf/belle

- docs/js/Configuration.jsx
- examples/js/RatingPlayground.jsx
- src/index.js
Hey Nik,
You might want to change description of behavior I have added. I am often not able to do good job at descriptions.
> doc(rating): adding rating related configurations to configuration page

- docs/js/ComboBoxDocumentation.jsx
- docs/js/RatingDocumentation.jsx
- docs/js/SelectDocumentation.jsx
- docs/js/TextInputDocumentation.jsx
- docs/js/ToggleDocumentation.jsx
- examples/js/ComboBoxPlayground.jsx
- examples/js/RatingPlayground.jsx
- examples/js/SelectPlayground.jsx
- examples/js/TextInputPlayground.jsx
- src/components/ComboBox.jsx
- src/components/Rating.jsx
- src/components/Select.jsx
- src/components/TextInput.jsx
- src/components/Toggle.jsx
- tests/__tests__/ComboBox-test.jsx
- tests/__tests__/Select-test.jsx
- tests/__tests__/TextInput-test.jsx
Hi Nik,
These are small changes mainly around handling of value/ valueLink/ defaultValue. We can plan a pairing session to discuss these before you merge.
> Minor fixes

- docs/js/ChoiceDocumentation.jsx
- docs/js/ToggleDocumentation.jsx
- examples/js/TogglePlayground.jsx
- src/components/Toggle.jsx
> feat(Toggle): deprecated checked and introduced value

- docs/js/ComboBoxDocumentation.jsx
- docs/js/RatingDocumentation.jsx
- src/components/ComboBox.jsx
- src/components/Rating.jsx
- src/style/combo-box.js
- src/utils/animation-frame-management.js
- tests/__tests__/ComboBox-test.jsx
Code changes look good enough to be merged...
> feat(ComboBox): code changes to show typeahead sort of text of options value in input box

- docs/js/ComboBoxDocumentation.jsx
- src/components/Button.jsx
- src/components/Card.jsx
- src/components/ComboBox.jsx
- src/components/Option.jsx
- src/components/Placeholder.jsx
- src/components/Rating.jsx
- src/components/Select.jsx
- src/components/Separator.jsx
- src/components/TextInput.jsx
- src/components/Toggle.jsx
Hey Nik...does this looks good to you, I can replicate it over other components.
....hmmm I think its fairly good...just replicating over other components ad updating PR
> refactor(Rating): changing method parameter 'props' to 'properties'

- docs/js/ButtonDocumentation.jsx
- docs/js/ComboBoxDocumentation.jsx
- docs/js/RatingDocumentation.jsx
- docs/js/SelectDocumentation.jsx
- docs/js/TextInputDocumentation.jsx
- docs/js/ToggleDocumentation.jsx
- src/components/ComboBox.jsx
- src/components/Select.jsx
- src/style/combo-box.js
- src/style/select.js
@jpuri can you double check this PR? I needed it for the Bootstrap styling.
> Fix select style

- docs/js/Configuration.jsx
- docs/js/RatingDocumentation.jsx
- src/components/Button.jsx
- src/components/ComboBox.jsx
- src/components/Option.jsx
- src/components/Placeholder.jsx
- src/components/Rating.jsx
- src/components/TextInput.jsx
- src/style/button.js
- src/style/combo-box.js
- src/style/option.js
- src/style/placeholder.js
- src/style/rating.js
- src/style/select.js
- src/style/toggle.js
Looks like I should not have done so much refactoring at this stage (I am not able to resist at time :) )
I have made double check to make sure nothing breaks.
> Fix styles

- docs/js/ComboBoxDocumentation.jsx
- src/components/ComboBox.jsx
- src/style/combo-box.js
Hey Nik,
I have not added 'caretFocusStyle' to docs: configuration, nor I have added 'onCaretClick' to props.
Probability that users would need it is really really low. Api for users I think should not be loaded with too many things, only those they would need (and will be able to read :) in docs).
> Combobox caret changes

- docs/js/Base.jsx
- docs/js/FormComponents.jsx
- docs/js/routes.jsx
Th content looks fine to me...but we can improve it further...
> Docs form component

- docs/js/ToggleDocumentation.jsx
- src/components/Toggle.jsx
Solves: https://github.com/nikgraf/belle/issues/66
> feat(Toggle): add tolerance area for touchmove

- src/components/TextInput.jsx
Hey Nik,
I created branch for this PR on top of other PR's branch. SO its showing that commit also....I do not wanted to remove it or else merge conflicts can come.
> Textinput fix

- src/components/Toggle.jsx
- src/style/button.js
- src/style/combo-box.js
- src/style/rating.js
- src/style/select.js
- src/style/text-input.js
- src/style/toggle.js
@jpuri very subtle animations :)
> style(ComboBox): add animation

- .eslintignore
- README.md
- package.json
- src/components/Button.jsx
- src/components/Card.jsx
- src/components/ComboBox.jsx
- src/components/Option.jsx
- src/components/Placeholder.jsx
- src/components/Rating.jsx
- src/components/Select.jsx
- src/components/Separator.jsx
- src/components/TextInput.jsx
- src/components/Toggle.jsx
- src/config/select.js
- src/utils/helpers.js
- src/utils/inject-style.js
- src/utils/union-class-names.js
Hey Nik...
Check the helpers file...does it look goo enough to you.
I still see some eslint errors, but I do not want to do any further changes. I am scared my changes will break something with existing code logic of these methods.
> refactor: deprecating underscore for src

- docs/js/SelectDocumentation.jsx
- src/utils/calculate-textarea-height.js
I am not sure if this is best way.... but its simple and works.
> fix(TextInput): setting minimal height of textarea

- docs/js/ComboBoxDocumentation.jsx
- examples/js/ComboBoxPlayground.jsx
- src/components/ComboBox.jsx
- tests/__tests__/ComboBox-test.jsx
Hey @nikgraf , does this name 'onInputMatch' for the new api method looks good ?
> Combobox changes

- CHANGELOG.md
- docs/js/ComboBoxDocumentation.jsx
- examples/js/ComboBoxPlayground.jsx
- src/components/ComboBox.jsx
- tests/__tests__/ComboBox-test.jsx
@jpuri I already merged another PR, but wanted to wait with the release because of this. Better to check it before we release a bad version.
> Improve naming

- docs/js/TextInputDocumentation.jsx
- src/components/TextInput.jsx
This allows limiting the amount of lines visible without knowing the exact dimensions in pixels.
> Add minRows and maxRows attributes for TextInput

- src/components/ComboBox.jsx
- src/components/Select.jsx
- src/config/select.js
- src/utils/helpers.js
- tests/__tests__/ComboBox-test.jsx
Hey @nikgraf ,
This PR has fix for Radium issue in ComboBox, you can review. I am still working on fixing it in Select and will soon update this PR.
> fix(ComboBox): supporting non-array structure for props.children

- src/utils/calculate-textarea-height.js
Thanks to @razh for this contribution to https://github.com/andreypopp/react-textarea-autosize/pull/51
> feat(TextInput): add text-rendering css property to properly calculate the height

- README.md
- package.json
- src/__tests__/ComboBox-test.js
- src/__tests__/Select-test.js
- src/__tests__/helpers-test.js
- src/components/Button.js
- src/components/ComboBox.js
- src/components/Option.js
- src/components/Placeholder.js
- src/components/Rating.js
- src/components/Select.js
- src/components/Separator.js
- src/components/TextInput.js
- src/components/Toggle.js
- src/utils/helpers.js
Used a codemod https://github.com/nikgraf/js-codemod/blob/master/transforms/replace-extend-with-spread.js for the first commit
> Refactor extend

- examples/index.js
- src/components/DatePicker.js
- src/index.js
- src/style/date-picker.js
@jpuri It's far from done, but getting close.
> Datepicker improvements

- src/config/select.js
fix for https://github.com/nikgraf/belle/issues/189
> fix(Select): positionOptions needs refactoring for React 0.14

- docs/theme/belle-with-classic-focus.js
- src/components/DatePicker.js
> Minor date picker changes

- src/__tests__/Button-test.js
- src/components/Button.js
the button improvements in preparation for 2.0.0 rc2
> Button improvements

- .eslintrc
- src/components/ActionArea.js
- src/components/Button.js
@jpuri I tested it on the iPhone today and this now finally fixes the hover issue (also for DatePicker)
> fix(ActionArea, Button): fix sticky hover behaviour

- src/components/DatePicker.js
@jpuri We missed one thing: touchEnd doesn't have touches as it's already done :smile:
> fix(DatePicker): make sure selecting a date works on touch devices

- src/components/ActionArea.js
- src/components/ComboBox.js
- src/components/DatePicker.js
- src/components/Rating.js
- src/components/Select.js
- src/components/TextInput.js
- src/components/Toggle.js
@nikgraf , this PR covers all components, but I will spend some more time again tomorrow on it to double check that no method is left out.
> Remove method bindings

- src/__tests__/Select-test.js
- src/components/SelectItem.js
i had to swap `TestUtils.Simulate.click` with `TestUtils.Simulate.mouseDown` in Select-test.js
> fixed tests for workaround suggested by @GuillaumeBadi in PR #324
